name: Daily Update

on:
  schedule:
    - cron: '30 12 * * *' # Se ejecuta a las 12:30 PM UTC todos los días

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      
    - name: Make a small change
      run: |
        echo "Última actualización: $(date)" >> README.md
        
    - name: Commit and push if there are changes
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add -A
        git commit -m "Daily update" -a || echo "No changes to commit"
        git push
